---
name: OIDC Demo

on: workflow_dispatch

permissions:
  contents: read

jobs:
  whoami:
    runs-on: ubuntu-latest
    # id-token: write lets the job request a GitHub ID token
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Who am I in AWS?
        run: |
          aws sts get-caller-identity
